---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slideshow-app-chart.fullname" . }}
type: Opaque
data:
  SESSION_SECRET: "{{ .Values.secrets.SESSION_SECRET | default "" | b64enc }}"
  APP_PASSWORD: "{{ .Values.secrets.APP_PASSWORD | default "" | b64enc }}"