apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slideshow-app-chart.fullname" . }}
  labels:
    {{- include "slideshow-app-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      {{- include "slideshow-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slideshow-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "slideshow-app-chart.fullname" . }}
          env:
            - name: GIN_MODE
              value: "release"
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-gsutil
          image: "google/cloud-sdk"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "tail -f /dev/null" ]
          envFrom:
            - secretRef:
                name: {{ include "slideshow-app-chart.fullname" . }}
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "slideshow-app-chart.fullname" . }}


