---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slideshow-app-chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacityGi }}Gi
  storageClassName: {{ .Values.storage.storageClassName }}
